import 'package:cloud_firestore/cloud_firestore.dart';

import '../../Network/Local/cacheHelper.dart';

var uid = CacheHelper.getData(key: 'uid');
DocumentSnapshot? interuser;
List<String> politicalKeywords = [
  'politics',
  'government',
  'election',
  'legislation',
  'policy',
  'president',
  'congress',
  'senate',
  'parliament',
  'democracy',
  'campaign',
  'corruption',
  'diplomacy',
  'parties',
  'politicians',
  'voting',
  'lobbying',
  'legislature',
  'policies',
  'political',
  'power',
  'rally',
  'republic',
  'dictatorship',
  'opposition',
  'candidate',
  'constitution',
  'democratic',
  'governance',
  'governor',
  'lawmaker',
  'minister',
  'reform',
  'statecraft',
  'supreme court',
  'treaty',
  'ballot',
  'civil rights',
  'coalition',
  'debate',
  'foreign policy',
  'impeachment',
  'liberty',
  'nationalism',
  'trump',
  'israel',
  'gaza',
  'ukraine',
  'russia',
  'palestine',
  'conflict',
  'occupation',
  'biden',
  'putin',
  'hamas',
];
List<String> businessKeywords = [
  'business',
  'economy',
  'finance',
  'market',
  'company',
  'industry',
  'stock',
  'investment',
  'entrepreneur',
  'start-up',
  'trade',
  'commerce',
  'profit',
  'revenue',
  'corporate',
  'marketplace',
  'capital',
  'shareholder',
  'entrepreneurship',
  'financial',
  'stock market',
  'economic',
  'merger',
  'acquisition',
  'startup',
  'bank',
  'enterprise',
  'productivity',
  'supply chain',
  'business model',
  'market research',
  'business plan',
  'business strategy',
  'entrepreneurial',
  'product development',
  'business growth',
  'globalization',
  'business sector',
  'business management',
  'business opportunity',
  'business venture',
];
List<String> technologyKeywords = [
  'technology',
  'tech',
  'innovation',
  'digital',
  'internet',
  'software',
  'hardware',
  'artificial intelligence',
  'AI',
  'machine learning',
  'ML',
  'data science',
  'blockchain',
  'cybersecurity',
  'cloud computing',
  'virtual reality',
  'VR',
  'augmented reality',
  'internet of things',
  'IoT',
  'automation',
  'robotics',
  'smart',
  'algorithm',
  'coding',
  'programming',
  'developer',
  'startup',
  'gadget',
  'social media',
  'mobile',
  'wireless',
  'ecommerce',
  'website',
  'algorithm',
  'network',
  'encryption',
  'big data',
  'nanotechnology',
  'quantum computing',
  'Tesla',
  'Microsoft',
  'Apple',
  'Amazon',
  'Google',
  'Facebook',
  'IBM',
  'Intel',
  'SpaceX',
  'Elon Musk',
  'Bill Gates',
  'Tim Cook',
  'Jeff Bezos',
  'Mark Zuckerberg',
  'Iphone',
  'Android',
];
List<String> entertainmentKeywords = [
  'Entertainment',
  'Celebrities',
  'Movies',
  'Music',
  'Television',
  'Gaming',
  'Gossip',
  'Red carpet',
  'Showbiz',
  'Pop culture',
  'Hollywood',
  'Fashion',
  'Celebrity interviews',
  'Awards',
  'Concerts',
  'Box office',
  'Tabloids',
  'Film festivals',
  'TV shows',
  'Streaming services',
  'Paparazzi',
  'Entertainment industry',
  'Stage performances',
  'Pop music',
  'Reality TV',
  'Comedians',
  'Theater',
  'Album releases',
  'Fashion trends',
  'Entertainment news',
  'Film premieres',
  'Song',
  'Brad Pitt',
  'Angelina Jolie',
  'Beyoncé',
  'Leonardo DiCaprio',
  'Jennifer Aniston',
  'Taylor Swift',
  'Keanu Reeves',
  'Rihanna',
  'Tom Hanks',
  'Scarlett Johansson',
  'Ye'
  'Soundtracks',
  'Characters',
  'Controllers',
  'Graphics',
  'Mods',
  'Streaming',
  'Culture',
  'Esports'
];
List<String> sportsKeywords = [
  'Golf',
  'Live soccer',
  'NBA scores',
  'NFL scores',
  'BBC Sport',
  'Sports',
  'MLB scores',
  'Formula 1',
  'NHL scores',
  'NBA standings',
  'NBA playoffs',
  'Boxing',
  'Super Bowl',
  'Football scores',
  'NBA games',
  'EPL table',
  'MLB standings',
  'Tennis',
  'Basketball',
  'World Cup',
  'Motocross',
  'Wrestling',
  'Darts',
  'March Madness',
  'Handball',
  'Baseball',
  'Rugby',
  'MMA',
  'Snooker',
  'Duke basketball',
  'Hockey',
  'Score',
];
List<String> spaceKeywords = [
  'Earth',
  'Solar system',
  'Asteroid',
  'Astronaut',
  'Galaxy',
  'Moon',
  'Alpha Centauri',
  'Andromeda Galaxy',
  'Black hole',
  'Comet',
  'Constellation',
  'Cosmic',
  'Exoplanet',
  'Gravity',
  'Interstellar',
  'Meteor',
  'Milky Way',
  'Nebula',
  'Orbit',
  'Planet',
  'Satellite',
  'Star',
  'Supernova',
  'Telescope',
  'Universe',
  'Celestial',
  'Cosmos',
  'Stellar',
  'Astrophysics',
  'Spacecraft',
  'Lunar',
  'Cosmonaut',
  'Cosmic rays',
  'Space exploration',
  'Event horizon',
];
List<String> healthKeywords = [
  'fitness',
  'nutrition',
  'wellness',
  'exercise',
  'diet',
  'weight loss',
  'mental health',
  'physical activity',
  'healthy lifestyle',
  'self-care',
  'stress management',
  'hydration',
  'sleep',
  'immune system',
  'vitamins',
  'meditation',
  'yoga',
  'cardio',
  'strength training',
  'calories',
  'healthcare',
  'well-being',
  'preventive care',
  'mindfulness',
  'nutrients',
  'workout',
  'health goals',
  'balanced diet',
  'fitness tracker',
  'active living',
  'health education',
  'health awareness',
  // Add more health-related terms as needed
];
