import 'package:cloud_firestore/cloud_firestore.dart';

import '../../Network/Local/cacheHelper.dart';

var uid = CacheHelper.getData(key: 'uid');
DocumentSnapshot? interuser;
List<String> politicalKeywords = [
  'politics',
  'government',
  'election',
  'legislation',
  'policy',
  'president',
  'congress',
  'senate',
  'parliament',
  'democracy',
  'campaign',
  'corruption',
  'diplomacy',
  'parties',
  'politicians',
  'voting',
  'lobbying',
  'legislature',
  'policies',
  'political',
  'power',
  'rally',
  'republic',
  'dictatorship',
  'opposition',
  'candidate',
  'constitution',
  'democratic',
  'governance',
  'governor',
  'lawmaker',
  'minister',
  'reform',
  'statecraft',
  'supreme court',
  'treaty',
  'ballot',
  'civil rights',
  'coalition',
  'debate',
  'foreign policy',
  'impeachment',
  'liberty',
  'nationalism',
  'trump',
  'israel',
  'gaza',
  'ukraine',
  'russia',
  'palestine',
  'conflict',
  'occupation',
  'biden',
  'putin',
];
List<String> businessKeywords = [
  'business',
  'economy',
  'finance',
  'market',
  'company',
  'industry',
  'stock',
  'investment',
  'entrepreneur',
  'start-up',
  'trade',
  'commerce',
  'profit',
  'revenue',
  'corporate',
  'marketplace',
  'capital',
  'shareholder',
  'entrepreneurship',
  'financial',
  'stock market',
  'economic',
  'merger',
  'acquisition',
  'startup',
  'bank',
  'enterprise',
  'productivity',
  'supply chain',
  'business model',
  'market research',
  'business plan',
  'business strategy',
  'entrepreneurial',
  'product development',
  'business growth',
  'globalization',
  'business sector',
  'business management',
  'business opportunity',
  'business venture',
];
List<String> technologyKeywords = [
  'technology',
  'tech',
  'innovation',
  'digital',
  'internet',
  'software',
  'hardware',
  'artificial intelligence',
  'AI',
  'machine learning',
  'ML',
  'data science',
  'blockchain',
  'cybersecurity',
  'cloud computing',
  'virtual reality',
  'VR',
  'augmented reality',
  'AR',
  'internet of things',
  'IoT',
  'automation',
  'robotics',
  'smart',
  'algorithm',
  'coding',
  'programming',
  'developer',
  'startup',
  'gadget',
  'social media',
  'mobile',
  'wireless',
  'ecommerce',
  'website',
  'algorithm',
  'network',
  'encryption',
  'big data',
  'nanotechnology',
  'quantum computing',
  'Tesla',
  'Microsoft',
  'Apple',
  'Amazon',
  'Google',
  'Facebook',
  'IBM',
  'Intel',
  'SpaceX',
  'Elon Musk',
  'Bill Gates',
  'Tim Cook',
  'Jeff Bezos',
  'Mark Zuckerberg',
];