// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl7tRMjMjdUfNm_WFz4ko_elkT_gN51cA',
    appId: '1:1062770465478:web:311f8dcd6e4f70c98615c7',
    messagingSenderId: '1062770465478',
    projectId: 'compass-media',
    authDomain: 'compass-media.firebaseapp.com',
    storageBucket: 'compass-media.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNyYTeOoqNcrVf6Lb9dfiMh8tUDgNNE5s',
    appId: '1:1062770465478:android:8b2b6c3165b837c38615c7',
    messagingSenderId: '1062770465478',
    projectId: 'compass-media',
    storageBucket: 'compass-media.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVvsiCBglz-tHBsJ_IOQ0yY_waAuP9M8',
    appId: '1:1062770465478:ios:6d915f230b96a29c8615c7',
    messagingSenderId: '1062770465478',
    projectId: 'compass-media',
    storageBucket: 'compass-media.appspot.com',
    iosBundleId: 'com.example.compassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHVvsiCBglz-tHBsJ_IOQ0yY_waAuP9M8',
    appId: '1:1062770465478:ios:598190c3b6f2089b8615c7',
    messagingSenderId: '1062770465478',
    projectId: 'compass-media',
    storageBucket: 'compass-media.appspot.com',
    iosBundleId: 'com.example.compassApp.RunnerTests',
  );
}
